---
title: "Assignment"
author: "Kuan Gao"
date: "2022-08-11"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fpp3)
library(forecast)
library(ggthemr)
```

```{r read data}
# Read in the monthly temperature data
tempcsv<-read.csv("MonthlyTemp.csv")

# Filter the data to only include years 2000 and later
b<-tempcsv%>%filter(Year>=2000)

# Create time series objects for the maximum, minimum, highest, and lowest temperatures
temp_max<-ts(tempcsv[,3],
           frequency=12,start=c(1950,1))

temp_min<-ts(tempcsv[,4],
           frequency=12,start=c(1950,1))

temp_high<-ts(tempcsv[,5],
           frequency=12,start=c(1950,1))

temp_low<-ts(tempcsv[,6],
           frequency=12,start=c(1950,1))

# Filter the data to only include years 1985 and later
temp1985<-tempcsv%>%filter(Year>=1985)

# Create time series objects for the maximum and minimum temperatures, starting from 1985
temp_max_1985<-ts(temp1985[,3],
           frequency=12,start=c(1985,1))
  
temp_min_1985<-ts(temp1985[,4],
           frequency=12,start=c(1985,1))

# Create a time plot of the maximum temperature data
autoplot(temp_max)

```

```{r averages}

#averages subset of the temperature data for the period 1985-2021

averages<-ts(temp1985[,c(3,4,5,6)],
frequency=12,start=c(1985,1))

#plot the average temperature over time

autoplot(averages)+ggtitle(" Teperature plots") +
ylab("Temperature °C")+xlab("Year")


```
```{r }
ggthemr("copper") # set ggplot theme

fit_stlmax<-stl(temp_max,s.window=13) # apply STL decomposition to original data
pdmax=autoplot(fit_stlmax)+ggtitle("Average Daily Max Temperature of a month - (STL components)")+ # plot the decomposition components
  theme(plot.title = element_text(hjust = 0.5))+
  ylab("Temperature °C")+xlab("Year")
pdmax

t<-pdmax$data%>%filter(parts=="trend") # extract the trend component

early<-t%>%filter(datetime<1980.8) # subset for the early time period
late<-t%>%filter(datetime>1995.8) # subset for the late time period

ggplot(data=t,aes(x=datetime,y=y))+geom_line(col="black")+xlab("Year")+ylab("Temperature °C")+
  ggtitle("Average Daily Max Temperature of a month - Trend (STL method) ")+theme(plot.title = element_text(hjust = 0.5))+
   geom_line(data=early,aes(x=datetime,y=y),col="red")+ # plot trend component and the two time period subsets in red
  geom_line(data=late,aes(x=datetime,y=y),col="red")

ggthemr('fresh') # set ggplot theme

plot(temp_max, col="gray", main="Average Daily Max Temperature of a month - Seasonally Adjusted (STL)", ylab="Seasonally Adjusted", xlab="Year") # plot the original data
lines(seasadj(fit_stlmax),col="red") # add the seasonally adjusted data from the STL decomposition in red
lines(x=c(1950,1980),y=c(18.6,20),col="black") # add black lines to indicate different time periods
lines(x=c(1980,1995),y=c(20,18.6),col="black")
lines(x=c(1995,2020),y=c(18.6,21),col="black")

legend(1948,30,legend=c("Original data", "SAJ data"),
       col=c("gray", "red"), lty=1, cex=0.5) # add legend to the plot


```

```{r min}
# set the theme of the plots to 'sky'
ggthemr('sky')

# apply stl decomposition to the time series of minimum temperature
fit_stlmin <- stl(temp_min, s.window=13)

# create a plot of the STL decomposition
pdmin <- autoplot(fit_stlmin) +
  ggtitle("Average Daily Min Temperature of a month - (STL components)") +
  theme(plot.title = element_text(hjust = 0.5)) +
  ylab("Temperature °C") + xlab("Year") +
  scale_colour_brewer()

# filter the data for the trend component of the STL decomposition
t <- pdmin$data %>% filter(parts == "trend")

# filter the data for the early, middle, and late periods
early <- t %>% filter(datetime < 1980.8)
late <- t %>% filter(datetime > 1986.8)
middle <- t %>% filter(datetime > 1988.3 & datetime < 1996.1)

# create a plot of the trend component of the time series
ggplot(data=t, aes(x=datetime, y=y)) +
  geom_line(col="blue") + 
  xlab("Year") + ylab("Temperature °C") +
  ggtitle("Average Daily Min Temperature of a month - (STL components)") +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_line(data=early, aes(x=datetime, y=y), col="black") +
  geom_line(data=late, aes(x=datetime, y=y), col="black") +
  geom_line(data=middle, aes(x=datetime, y=y), col="blue")

# create a plot of the time series with the seasonal component removed
plot(temp_min, col="gray", main="Average Daily Min Temperature of a month - (STL components)", ylab="Seasonally Adjusted", xlab="Year")
lines(seasadj(fit_stlmin), col="blue")
lines(x=c(1950,1980), y=c(8.6,10), col="black")
lines(x=c(1980,1988), y=c(10,8), col="black")
lines(x=c(1988,2020), y=c(8,11), col="black")
legend(1948,17.6, legend=c("Original data", "SAJ data"),
       col=c("gray", "blue"), lty=1, cex=0.5)



```
```{r seasonal data}
ggthemr("greyscale")


#low

fit_stllow<-stl(temp_low,t.window=21,s.window=13)
pdl=autoplot(fit_stllow)


ggsubseriesplot(seasonal(fit_stlmax)) + 
  ggtitle("Seasonal Variations(STL component): Average daily max temperature") +
  ylab("Seasonal")+
  theme(plot.title = element_text(hjust = 0.5))

ggsubseriesplot(seasonal(fit_stlmin)) + 
  ggtitle("Seasonal Variations(STL component): Average daily min temperature") + 
  ylab("Seasonal")+
  theme(plot.title = element_text(hjust = 0.5))


ggsubseriesplot(seasonal(fit_stlhigh)) + 
  ggtitle("Seasonal Variations(STL component): Highest of months") + ylab("Seasonal")+
  theme(plot.title = element_text(hjust = 0.5))


ggsubseriesplot(seasonal(fit_stllow)) + 
  ggtitle("Seasonal Variations(STL component): Lowest of months") + ylab("Seasonal")+
  theme(plot.title = element_text(hjust = 0.5))

```

```{r Fitting the model}
####MAX MODEL
fit<-tslm(temp_max~trend+season)
summary(fit)

summer=c(10,11,12)
fit3<-tslm(temp_max~trend+season+
             I((season==summer)*trend)+I(pmax(trend-35*12,0))+I(pmax(trend-45*12,0)))

CV(fit3)
summary(fit3)

ggthemr("light")
autoplot(temp_max, series="Data") +
  autolayer(fitted(fit), series="Fitted") +
  xlab("Year") + ylab("Temperature °C") +
  ggtitle("Temperatures")
ggthemr("light")
autoplot(temp_max, series="Data") +
  autolayer(fitted(fit3), series="Fitted") +
  xlab("Year") + ylab("Temperature °C") +
  ggtitle("Temperatures")


fcast <- forecast(fit3,h=21*12)
plot(fcast, main="Forecasts of termperature using quadratic regression")
```

```{r fitting the model minimum}
####MIN MODEL
fit<-tslm(temp_min~trend+season)



summe=c(10,11,12)
fit3<-tslm(temp_min~trend+season+
             I((season==11)*trend)+I(pmax(trend-30*12,0))+I(pmax(trend-40*12,0)))

summary(fit)
summary(fit3)

ggthemr("light")
autoplot(temp_min, series="Data") +
  autolayer(fitted(fit), series="Fitted") +
  xlab("Year") + ylab("Temperature °C") +
  ggtitle("Temperatures")
ggthemr("light")
autoplot(temp_min, series="Data") +
  autolayer(fitted(fit3), series="Fitted") +
  xlab("Year") + ylab("Temperature °C") +
  ggtitle("Temperatures")


fcast <- forecast(fit3,h=21*12)
plot(fcast, main="Forecasts of termperature using quadratic regression")


```
```{r forecasting}

########MAX
maxtrain<-window(temp_max,start=c(1950,1),end=c(2009,12))
maxout<-window(temp_max,start=c(2010,1),end=c(2021,12))


fit_train<-tslm(maxtrain~trend+season)
fcast <- forecast(fit_train,h=12*12)
plot(fcast, main="Forecasts of temperature using pair-wise regression")
measure1=accuracy(fcast,maxout)

summer=c(10,11,12)
fit_train2<-tslm(maxtrain~trend+season+I(pmax(trend-35*12,0))+I((season==summer)*trend))
fcast <- forecast(fit_train2,h=12*12)
plot(fcast, main="Forecasts of temperature using pair-wise regression")
measure2=accuracy(fcast,maxout)
summary(fit_train2)

fit_stlmax<-stl(maxtrain,s.window=13)

fcast_rw <- forecast(fit_stlmax, method="naive", h=12*12)
plot(fcast_rw, ylab="Retail Sales")
measure3=accuracy(fcast_rw,maxout)

# random walk with drift 
fcast_rwd <- forecast(fit_stlmax, method="rwdrift", h=12*12)
plot(fcast_rwd, ylab="Retail Sales")
measure4=accuracy(fcast_rwd,maxout)

# exponential smoothing 
fcast_ets <- forecast(fit_stlmax, method="ets", h=12*12)
plot(fcast_ets, ylab="Retail Sales")
measure5=accuracy(fcast_ets,maxout)

# ARIMA model 
fcast_arima <- forecast(fit_stlmax, method="arima", h=12*12) 
plot(fcast_arima, ylab="Retail Sales")
measure6=accuracy(fcast_arima,maxout)

```
```{r forecast min}
######MIN

mintrain<-window(temp_min,start=c(1950,1),end=c(2009,12))
minout<-window(temp_min,start=c(2010,1),end=c(2021,12))


fit_train<-tslm(mintrain~trend+season)

fcast1 <- forecast(fit_train,h=12*12)
plot(fcast, main="Forecasts of temperature using pair-wise regression")
measure1=accuracy(fcast1,minout)

summer=c(11,12,1,2)
fit_train2<-tslm(mintrain~trend+season+I(pmax(trend-30*12,0))+I(pmax(trend-40*12,0))+I((season==11)*trend))
summary(fit_train2)
fcast2 <- forecast(fit_train2,h=12*12)
plot(fcast, main="Forecasts of temperature using pair-wise regression")
measure2=accuracy(fcast2,minout)


fit_stlmin<-stl(mintrain,s.window=13)

fcast_rw <- forecast(fit_stlmin, method="naive", h=12*12)
plot(fcast_rw, ylab="Retail Sales")
measure3=accuracy(fcast_rw,minout)

# random walk with drift (Lecture page 44)
fcast_rwd <- forecast(fit_stlmin, method="rwdrift", h=12*12)
plot(fcast_rwd, ylab="Retail Sales")
measure4=accuracy(fcast_rwd,minout)

# exponential smoothing (Lecture page 45)
fcast_ets <- forecast(fit_stlmin, method="ets", h=12*12)
plot(fcast_ets, ylab="Retail Sales")
measure5=accuracy(fcast_ets,minout)

# ARIMA model (Lecture page 46)
fcast_arima <- forecast(fit_stlmin, method="arima", h=12*12) 
plot(fcast_arima, ylab="Retail Sales")
measure6=accuracy(fcast_arima,minout)


```



```{r forecasting}

maxtrain<-window(temp_max,start=c(1950,1),end=c(1999,12))
maxout<-window(temp_max,start=c(2000,1),end=c(2020,12))

autoplot(stl(maxtrain,s.window=13))

fit_train<-tslm(maxtrain~trend+season+I(trend^3)+I(trend^2)+I(pmax(trend-30*12,0))+I((season==summer)*trend))
fcast <- forecast(fit_train,h=21*12)
plot(fcast, main="Forecasts of beer production using quadratic regression")
measure1=accuracy(fcast,maxout)


fit_train3<-tslm(maxtrain~trend+season+I(trend^3)+I(trend^2)+I(pmax(trend-30*12,0)))
fcast3 <- forecast(fit_train3,h=21*12)
plot(fcast2, main="Forecasts of beer production using quadratic regression")
measure3=accuracy(fcast3,maxout)



fit_train2<-tslm(maxtrain~trend+season+I(trend^2))
fcast2 <- forecast(fit_train2,h=21*12)
plot(fcast2, main="Forecasts of beer production using quadratic regression")
measure2=accuracy(fcast2,maxout)


fit_train4<-tslm(maxtrain~trend+season)
fcast4 <- forecast(fit_train4,h=21*12)
plot(fcast4, main="Forecasts of beer production using quadratic regression")
measure4=accuracy(fcast4,maxout)
CV(fit_train)
CV(fit_train2)
CV(fit_train3)
CV(fit_train4) 

measure1
measure3
measure2
measure4



```



```{r }
# fit and plot model with linear trend and seasonal component
fit <- tslm(temp_max ~ trend + season)
summary(fit)

# fit and plot model with quadratic trend and seasonal component
fit2 <- tslm(temp_max ~ trend + season + I(trend^2))
summary(fit2)

# fit and plot model with cubic trend, quadratic and cubic seasonality, and additional predictor
fit3 <- tslm(temp_max ~ trend + season + I(trend^2) + I(trend^3) + 
             I(pmax(trend-37*12,0)^2) + I(pmax(trend-8*12,0)^3) + 
             I(trend > 33.5*12 & trend < 35.6*12))
summary(fit3)

# check residuals for fit3
checkresiduals(fit3)

# plot original data and model predictions
ggthemr("light")
autoplot(temp_max, series="Data") +
  autolayer(fitted(fit3), series="Fitted") +
  xlab("Year") + ylab("Temperature °C") +
  ggtitle("Temperatures")

# fit and plot model with linear trend and seasonal component for temp_min
fit_min <- tslm(temp_min ~ trend + season)
summary(fit_min)

# fit and plot model with quadratic trend and seasonal component for temp_min
fit2_min <- tslm(temp_min ~ trend + season + I(trend^2))
summary(fit2_min)

# fit and plot model with cubic trend, quadratic and cubic seasonality, and additional predictor for temp_min
fit3_min <- tslm(temp_min ~ trend + season + I(trend^2) + I(trend^3) + 
                 I(pmax(trend-37*12,0)^2) + I(pmax(trend-8*12,0)^3) + 
                 I(trend > 33.5*12 & trend < 35.6*12))
summary(fit3_min)

# check residuals for fit3_min
checkresiduals(fit3_min)

# plot original data and model predictions for temp_min
ggthemr("light")
autoplot(temp_min, series="Data") +
  autolayer(fitted(fit3_min), series="Fitted") +
  xlab("Year") + ylab("Temperature °C") +
  ggtitle("Temperatures")

# create data frame with residuals and other variables for temp_max
df <- as.data.frame(temp_max)
df[,"Residuals"]  <- as.numeric(residuals(fit))

# create scatterplots of residuals against other variables for temp_max
p1 <- ggplot(df, aes(x=, y=Residuals)) +
  geom_point()
p2 <- ggplot(df, aes(x=Production, y=Residuals)) +
  geom_point()
p3 <- ggplot(df, aes(x=Savings, y=Residuals)) +
  geom_point()
p4 <- ggplot(df, aes(x=Unemployment, y=Residuals)) +
  geom_point()




```





